### ISSUE TITLE
Error in workflow 'Open JumpDesktop Connection'

### ISSUE THREAD

**Issue by austinarchibald** [yaoxinghuo/alfred-jumpdesktop-workflow#5]
Been using this workflow for awhile now with no issues, this just popped up now. Might be connected to recent update to Sonoma 14.1. 

<img width="764" alt="image" src="https://github.com/yaoxinghuo/alfred-jumpdesktop-workflow/assets/12240843/32531ba8-684b-4927-bb34-a72f0b71c385">

Thanks in advance!

Log:

```
[14:07:27.396] Logging Started...
[14:07:32.320] Open JumpDesktop Connection[Script Filter] Queuing argument 'h'
[14:07:32.365] Open JumpDesktop Connection[Script Filter] Queuing argument 'ho'
[14:07:32.498] Open JumpDesktop Connection[Script Filter] Script with argv 'h' finished
[14:07:32.503] ERROR: Open JumpDesktop Connection[Script Filter] Code 1: .
14:07:32 workflow.py:2093 DEBUG    ---------- Open JumpDesktop Connection (1.0.3) ----------
14:07:32 workflow.py:2114 ERROR    'Username'
Traceback (most recent call last):
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 67, in main
    connections = wf.cached_data('connections', read_connections, max_age=30)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 1723, in cached_data
    data = data_func()
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 37, in read_connections
    (protocol_switch(dict_content['ProtocolTypeCode']), dict_content['TcpHostName'], dict_content['Username'])
KeyError: 'Username'
14:07:32 workflow.py:2136 DEBUG    ---------- finished in 0.027s ----------
[14:07:32.506] Open JumpDesktop Connection[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Open JumpDesktop Connection'</title><subtitle>'Username'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[14:07:32.580] Open JumpDesktop Connection[Script Filter] Script with argv 'ho' finished
[14:07:32.589] ERROR: Open JumpDesktop Connection[Script Filter] Code 1: .
14:07:32 workflow.py:2093 DEBUG    ---------- Open JumpDesktop Connection (1.0.3) ----------
14:07:32 workflow.py:2114 ERROR    'Username'
Traceback (most recent call last):
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 67, in main
    connections = wf.cached_data('connections', read_connections, max_age=30)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 1723, in cached_data
    data = data_func()
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 37, in read_connections
    (protocol_switch(dict_content['ProtocolTypeCode']), dict_content['TcpHostName'], dict_content['Username'])
KeyError: 'Username'
14:07:32 workflow.py:2136 DEBUG    ---------- finished in 0.015s ----------
[14:07:32.591] Open JumpDesktop Connection[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Open JumpDesktop Connection'</title><subtitle>'Username'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[14:07:32.830] Open JumpDesktop Connection[Script Filter] Queuing argument 'hom'
[14:07:32.915] Open JumpDesktop Connection[Script Filter] Queuing argument 'home'
[14:07:32.960] Open JumpDesktop Connection[Script Filter] Script with argv 'hom' finished
[14:07:32.966] ERROR: Open JumpDesktop Connection[Script Filter] Code 1: .
14:07:32 workflow.py:2093 DEBUG    ---------- Open JumpDesktop Connection (1.0.3) ----------
14:07:32 workflow.py:2114 ERROR    'Username'
Traceback (most recent call last):
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 67, in main
    connections = wf.cached_data('connections', read_connections, max_age=30)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 1723, in cached_data
    data = data_func()
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 37, in read_connections
    (protocol_switch(dict_content['ProtocolTypeCode']), dict_content['TcpHostName'], dict_content['Username'])
KeyError: 'Username'
14:07:32 workflow.py:2136 DEBUG    ---------- finished in 0.016s ----------
[14:07:32.969] Open JumpDesktop Connection[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Open JumpDesktop Connection'</title><subtitle>'Username'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[14:07:33.041] Open JumpDesktop Connection[Script Filter] Script with argv 'home' finished
[14:07:33.051] ERROR: Open JumpDesktop Connection[Script Filter] Code 1: .
14:07:33 workflow.py:2093 DEBUG    ---------- Open JumpDesktop Connection (1.0.3) ----------
14:07:33 workflow.py:2114 ERROR    'Username'
Traceback (most recent call last):
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 67, in main
    connections = wf.cached_data('connections', read_connections, max_age=30)
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/workflow/workflow.py", line 1723, in cached_data
    data = data_func()
  File "/Users/austin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A3D9512F-242F-42BD-9AFA-578E9870102A/ConnectionSearcher.py", line 37, in read_connections
    (protocol_switch(dict_content['ProtocolTypeCode']), dict_content['TcpHostName'], dict_content['Username'])
KeyError: 'Username'
14:07:33 workflow.py:2136 DEBUG    ---------- finished in 0.015s ----------
[14:07:33.053] Open JumpDesktop Connection[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Open JumpDesktop Connection'</title><subtitle>'Username'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

**Comment by yaoxinghuo** [comment]
One of your JumpDesktop connection profile may not have 'Username' field, I have changed my code to check if username exists, please replace your `ConnectionSearcher.py`'s file content with: `https://raw.githubusercontent.com/yaoxinghuo/alfred-jumpdesktop-workflow/master/ConnectionSearcher.py` and try again.

**Comment by austinarchibald** [comment]
Thank you. I just looked through my JumpDesktop profiles, and each one has Username properly filled in - so that's weird. Also, how do I edit ConnectionSearcher.py? Where is it stored? I checked `~/Library/Application Support/Alfred/Workflow Data/com.terrynow.jumpdesktop_alfred` and only see a `settings.json` file. I also tried downloading the `Open.JumpDesktop.Connection.alfredworkflow` again, anticipating I might be able to Show Package Contents and edit it that way, but not available. Thank you!

**Comment by yaoxinghuo** [comment]
Hi, open alfred preferences, follow the screenshot, you can location the `ConnectionSearcher.py`:
<img width="365" alt="image" src="https://github.com/yaoxinghuo/alfred-jumpdesktop-workflow/assets/69723/448cd27d-f34e-44fb-9318-f1bdccb2b9fd">

If this does not work, you may share your connection profile(.jump file) matched 'home', so I can debug. (delete sensitive data before you upload)

**Comment by austinarchibald** [comment]
Replacing that file with your latest changes worked! Thanks so much for your help.
